# Generated by Django 2.0 on 2017-12-24 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedWebsites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('source', models.URLField(blank=True, max_length=250)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('favorite', models.BooleanField(default=False)),
                ('tosort', models.BooleanField(default=False)),
                ('toread', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, max_length=250)),
                ('favicon_url', models.URLField(blank=True, max_length=250)),
                ('friends', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('added_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('edit_datetime', 'added_datetime'),
            },
        ),
        migrations.CreateModel(
            name='BookmarksUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_bk_view', models.CharField(choices=[('BOX', 'Boxes'), ('BLI', 'Big List'), ('SLI', 'Small List')], default='BLI', max_length=3)),
                ('open_bk_option', models.CharField(choices=[('TAB', 'New tab'), ('WIN', 'New Window')], default='TAB', max_length=3)),
                ('user_level', models.CharField(choices=[('FREE', 'Free'), ('PAID', 'Paid'), ('CORP', 'Corporate'), ('ORGS', 'Organisation')], default='CORP', max_length=4)),
                ('public', models.BooleanField(default=False)),
                ('last_data_clean', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('icon_code', models.CharField(max_length=20)),
                ('added_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_datetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shared', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('added_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('edit_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_directories', to='bookmarks.Folder')),
            ],
            options={
                'ordering': ('edit_datetime', 'added_datetime'),
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('notification_type', models.CharField(blank=True, choices=[('FRIEND', 'Friend Request'), ('SHARE', 'Shared with you'), ('MESSAGE', 'Message'), ('FOLDER', 'Folder activity')], max_length=7, null=True)),
                ('name', models.CharField(max_length=20)),
                ('short_text', models.CharField(max_length=75)),
                ('added_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtype', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='website_type',
            field=models.ManyToManyField(blank=True, to='bookmarks.WebsiteType'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='categories',
            field=models.ManyToManyField(blank=True, to='bookmarks.Category'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='bookmarks.Keyword'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'url')},
        ),
    ]
