# Generated by Django 2.0 on 2017-12-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='folder',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmarks.Folder'),
        ),
    ]
