# Generated by Django 2.0 on 2017-12-24 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20171224_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='bookmarks.Folder'),
        ),
    ]
